/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ink: 'var(--ink)',
        'ink-soft': 'var(--ink-soft)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        line: 'var(--line)',
        fg: 'var(--fg)',
        'fg-muted': 'var(--fg-muted)',
        'fg-dim': 'var(--fg-dim)',
        primary: 'var(--primary)',
        'primary-tint': 'var(--primary-tint)',
        'primary-ink': 'var(--primary-ink)',
        'primary-foreground': 'var(--primary-ink)',
        amber: 'var(--amber)',
        'amber-tint': 'var(--amber-tint)',
        'amber-foreground': 'var(--amber)',
        teal: 'var(--teal)',
        'teal-tint': 'var(--teal-tint)',
        'teal-foreground': 'var(--teal)',
        red: 'var(--red)',
        'red-tint': 'var(--red-tint)',
        'red-foreground': 'var(--red)',
        blue: 'var(--blue)',
        'blue-tint': 'var(--blue-tint)',
        'blue-foreground': 'var(--blue)',
        purple: 'var(--purple)',
        'purple-tint': 'var(--purple-tint)',
        'purple-foreground': 'var(--purple)',
        cyan: 'var(--cyan)',
        'cyan-tint': 'var(--cyan-tint)',
        'cyan-foreground': 'var(--cyan)',
      },
      spacing: {
        xs: 'var(--spacing-xs)',
        sm: 'var(--spacing-sm)',
        md: 'var(--spacing-md)',
        lg: 'var(--spacing-lg)',
        xl: 'var(--spacing-xl)',
        xxl: 'var(--spacing-xxl)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        headline: ['var(--font-headline)', 'system-ui', 'sans-serif'],
        title: ['var(--font-title)', 'system-ui', 'sans-serif'],
        body: ['var(--font-body)', 'system-ui', 'sans-serif'],
        label: ['var(--font-label)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'system-ui', 'monospace'],
      },
      fontSize: {
        base: ['var(--font-body)', 'var(--line-height-body)'],
        lg: ['var(--font-title)', 'var(--line-height-title)'],
        xl: ['var(--font-headline)', 'var(--line-height-headline)'],
        '2xl': ['var(--font-display)', 'var(--line-height-display)'],
      },
      fontWeight: {
        display: 'var(--font-weight-display)',
        headline: 'var(--font-weight-headline)',
        title: 'var(--font-weight-title)',
        body: 'var(--font-weight-body)',
        label: 'var(--font-weight-label)',
        mono: 'var(--font-weight-mono)',
      },
      lineHeight: {
        display: 'var(--line-height-display)',
        headline: 'var(--line-height-headline)',
        title: 'var(--line-height-title)',
        body: 'var(--line-height-body)',
        label: 'var(--line-height-label)',
        mono: 'var(--line-height-mono)',
      },
      letterSpacing: {
        display: 'var(--letter-spacing-display)',
        headline: 'var(--letter-spacing-headline)',
        title: 'var(--letter-spacing-title)',
        body: 'var(--letter-spacing-body)',
        label: 'var(--letter-spacing-label)',
        mono: 'var(--letter-spacing-mono)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography')
  ],
}
